/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UtilisateursRouteImport } from './routes/utilisateurs'
import { Route as StatistiquesRouteImport } from './routes/statistiques'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SignalementsRouteImport } from './routes/signalements'
import { Route as ParametresRouteImport } from './routes/parametres'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as InstitutionsRouteImport } from './routes/institutions'
import { Route as IncidentsRouteImport } from './routes/incidents'
import { Route as FactCheckingRouteImport } from './routes/fact-checking'
import { Route as ConnexionRouteImport } from './routes/connexion'
import { Route as ConnaissancesRouteImport } from './routes/connaissances'
import { Route as CarteRouteImport } from './routes/carte'
import { Route as AuditRouteImport } from './routes/audit'
import { Route as AnalyseIaRouteImport } from './routes/analyse-ia'
import { Route as AlertesRouteImport } from './routes/alertes'
import { Route as AdministrationRouteImport } from './routes/administration'
import { Route as IndexRouteImport } from './routes/index'

const UtilisateursRoute = UtilisateursRouteImport.update({
  id: '/utilisateurs',
  path: '/utilisateurs',
  getParentRoute: () => rootRouteImport,
} as any)
const StatistiquesRoute = StatistiquesRouteImport.update({
  id: '/statistiques',
  path: '/statistiques',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SignalementsRoute = SignalementsRouteImport.update({
  id: '/signalements',
  path: '/signalements',
  getParentRoute: () => rootRouteImport,
} as any)
const ParametresRoute = ParametresRouteImport.update({
  id: '/parametres',
  path: '/parametres',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const InstitutionsRoute = InstitutionsRouteImport.update({
  id: '/institutions',
  path: '/institutions',
  getParentRoute: () => rootRouteImport,
} as any)
const IncidentsRoute = IncidentsRouteImport.update({
  id: '/incidents',
  path: '/incidents',
  getParentRoute: () => rootRouteImport,
} as any)
const FactCheckingRoute = FactCheckingRouteImport.update({
  id: '/fact-checking',
  path: '/fact-checking',
  getParentRoute: () => rootRouteImport,
} as any)
const ConnexionRoute = ConnexionRouteImport.update({
  id: '/connexion',
  path: '/connexion',
  getParentRoute: () => rootRouteImport,
} as any)
const ConnaissancesRoute = ConnaissancesRouteImport.update({
  id: '/connaissances',
  path: '/connaissances',
  getParentRoute: () => rootRouteImport,
} as any)
const CarteRoute = CarteRouteImport.update({
  id: '/carte',
  path: '/carte',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditRoute = AuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyseIaRoute = AnalyseIaRouteImport.update({
  id: '/analyse-ia',
  path: '/analyse-ia',
  getParentRoute: () => rootRouteImport,
} as any)
const AlertesRoute = AlertesRouteImport.update({
  id: '/alertes',
  path: '/alertes',
  getParentRoute: () => rootRouteImport,
} as any)
const AdministrationRoute = AdministrationRouteImport.update({
  id: '/administration',
  path: '/administration',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/administration': typeof AdministrationRoute
  '/alertes': typeof AlertesRoute
  '/analyse-ia': typeof AnalyseIaRoute
  '/audit': typeof AuditRoute
  '/carte': typeof CarteRoute
  '/connaissances': typeof ConnaissancesRoute
  '/connexion': typeof ConnexionRoute
  '/fact-checking': typeof FactCheckingRoute
  '/incidents': typeof IncidentsRoute
  '/institutions': typeof InstitutionsRoute
  '/notifications': typeof NotificationsRoute
  '/parametres': typeof ParametresRoute
  '/signalements': typeof SignalementsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/statistiques': typeof StatistiquesRoute
  '/utilisateurs': typeof UtilisateursRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/administration': typeof AdministrationRoute
  '/alertes': typeof AlertesRoute
  '/analyse-ia': typeof AnalyseIaRoute
  '/audit': typeof AuditRoute
  '/carte': typeof CarteRoute
  '/connaissances': typeof ConnaissancesRoute
  '/connexion': typeof ConnexionRoute
  '/fact-checking': typeof FactCheckingRoute
  '/incidents': typeof IncidentsRoute
  '/institutions': typeof InstitutionsRoute
  '/notifications': typeof NotificationsRoute
  '/parametres': typeof ParametresRoute
  '/signalements': typeof SignalementsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/statistiques': typeof StatistiquesRoute
  '/utilisateurs': typeof UtilisateursRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/administration': typeof AdministrationRoute
  '/alertes': typeof AlertesRoute
  '/analyse-ia': typeof AnalyseIaRoute
  '/audit': typeof AuditRoute
  '/carte': typeof CarteRoute
  '/connaissances': typeof ConnaissancesRoute
  '/connexion': typeof ConnexionRoute
  '/fact-checking': typeof FactCheckingRoute
  '/incidents': typeof IncidentsRoute
  '/institutions': typeof InstitutionsRoute
  '/notifications': typeof NotificationsRoute
  '/parametres': typeof ParametresRoute
  '/signalements': typeof SignalementsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/statistiques': typeof StatistiquesRoute
  '/utilisateurs': typeof UtilisateursRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/administration'
    | '/alertes'
    | '/analyse-ia'
    | '/audit'
    | '/carte'
    | '/connaissances'
    | '/connexion'
    | '/fact-checking'
    | '/incidents'
    | '/institutions'
    | '/notifications'
    | '/parametres'
    | '/signalements'
    | '/sitemap.xml'
    | '/statistiques'
    | '/utilisateurs'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/administration'
    | '/alertes'
    | '/analyse-ia'
    | '/audit'
    | '/carte'
    | '/connaissances'
    | '/connexion'
    | '/fact-checking'
    | '/incidents'
    | '/institutions'
    | '/notifications'
    | '/parametres'
    | '/signalements'
    | '/sitemap.xml'
    | '/statistiques'
    | '/utilisateurs'
  id:
    | '__root__'
    | '/'
    | '/administration'
    | '/alertes'
    | '/analyse-ia'
    | '/audit'
    | '/carte'
    | '/connaissances'
    | '/connexion'
    | '/fact-checking'
    | '/incidents'
    | '/institutions'
    | '/notifications'
    | '/parametres'
    | '/signalements'
    | '/sitemap.xml'
    | '/statistiques'
    | '/utilisateurs'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdministrationRoute: typeof AdministrationRoute
  AlertesRoute: typeof AlertesRoute
  AnalyseIaRoute: typeof AnalyseIaRoute
  AuditRoute: typeof AuditRoute
  CarteRoute: typeof CarteRoute
  ConnaissancesRoute: typeof ConnaissancesRoute
  ConnexionRoute: typeof ConnexionRoute
  FactCheckingRoute: typeof FactCheckingRoute
  IncidentsRoute: typeof IncidentsRoute
  InstitutionsRoute: typeof InstitutionsRoute
  NotificationsRoute: typeof NotificationsRoute
  ParametresRoute: typeof ParametresRoute
  SignalementsRoute: typeof SignalementsRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  StatistiquesRoute: typeof StatistiquesRoute
  UtilisateursRoute: typeof UtilisateursRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/utilisateurs': {
      id: '/utilisateurs'
      path: '/utilisateurs'
      fullPath: '/utilisateurs'
      preLoaderRoute: typeof UtilisateursRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/statistiques': {
      id: '/statistiques'
      path: '/statistiques'
      fullPath: '/statistiques'
      preLoaderRoute: typeof StatistiquesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signalements': {
      id: '/signalements'
      path: '/signalements'
      fullPath: '/signalements'
      preLoaderRoute: typeof SignalementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parametres': {
      id: '/parametres'
      path: '/parametres'
      fullPath: '/parametres'
      preLoaderRoute: typeof ParametresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/institutions': {
      id: '/institutions'
      path: '/institutions'
      fullPath: '/institutions'
      preLoaderRoute: typeof InstitutionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/incidents': {
      id: '/incidents'
      path: '/incidents'
      fullPath: '/incidents'
      preLoaderRoute: typeof IncidentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fact-checking': {
      id: '/fact-checking'
      path: '/fact-checking'
      fullPath: '/fact-checking'
      preLoaderRoute: typeof FactCheckingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/connexion': {
      id: '/connexion'
      path: '/connexion'
      fullPath: '/connexion'
      preLoaderRoute: typeof ConnexionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/connaissances': {
      id: '/connaissances'
      path: '/connaissances'
      fullPath: '/connaissances'
      preLoaderRoute: typeof ConnaissancesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/carte': {
      id: '/carte'
      path: '/carte'
      fullPath: '/carte'
      preLoaderRoute: typeof CarteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audit': {
      id: '/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analyse-ia': {
      id: '/analyse-ia'
      path: '/analyse-ia'
      fullPath: '/analyse-ia'
      preLoaderRoute: typeof AnalyseIaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alertes': {
      id: '/alertes'
      path: '/alertes'
      fullPath: '/alertes'
      preLoaderRoute: typeof AlertesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/administration': {
      id: '/administration'
      path: '/administration'
      fullPath: '/administration'
      preLoaderRoute: typeof AdministrationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdministrationRoute: AdministrationRoute,
  AlertesRoute: AlertesRoute,
  AnalyseIaRoute: AnalyseIaRoute,
  AuditRoute: AuditRoute,
  CarteRoute: CarteRoute,
  ConnaissancesRoute: ConnaissancesRoute,
  ConnexionRoute: ConnexionRoute,
  FactCheckingRoute: FactCheckingRoute,
  IncidentsRoute: IncidentsRoute,
  InstitutionsRoute: InstitutionsRoute,
  NotificationsRoute: NotificationsRoute,
  ParametresRoute: ParametresRoute,
  SignalementsRoute: SignalementsRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  StatistiquesRoute: StatistiquesRoute,
  UtilisateursRoute: UtilisateursRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
